# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3129cf8b299431eb1e913a0838465ed50b3d64bc167e8b5e5d4152419058a4d708afad81bd67f33800c989088794d4a6719f5bcc58776091d3e9c325fc8b6ad

test:
  secret_key_base: 9ba9c453db20360b8e51708d7ff444bebd3b1a3e32194d78338b68dcaa527f4ac40a124b19c92ffc7cc74211cc9e9908ba69a077fd5f067c8f61e7eeabd5d403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
